version: '3'
services:
  go:
    build:
      context: .
      dockerfile: go.docker
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/go/src/PNTNT/backend
    stdin_open: true
    tty: true
    command: /bin/bash
  vue:
    build:
      context: .
      dockerfile: vue.docker
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/PNTNT/frontend
    stdin_open: true
    tty: true
    command: /bin/bash